# permissions to do viewer applicationdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationdemo-viewer-role
rules:
- apiGroups:
  - apps.yufan.com
  resources:
  - applicationdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.yufan.com
  resources:
  - applicationdemoes/status
  verbs:
  - get
